package com.example.domain.usecase.boarding

import com.example.domain.BuildConfig
import com.example.domain.model.BoardingPass
import javax.inject.Inject

/**
 * Produces the QR code payload for a boarding pass.
 *
 * The QR code contains only the [passId]
 * prefixed with "CHECKIN_PASS:".  When scanned, the reader app calls
 * POST /api/boarding/verify with the passId so the server validates
 * the reservation no sensitive data is embedded in the QR itself.
 *
 * If the boarding pass was generated by the server, [qrCodeData] already
 * contains the correct payload; we return it directly.
 * If for some reason the pass has no [qrCodeData] (offline mock), we
 * reconstruct the payload from [passId].
 */
class GenerateQRCodeUseCase @Inject constructor() {

    operator fun invoke(boardingPass: BoardingPass): String {
        // Server-generated passes already carry the correct payload
        /*if (!boardingPass.qrCodeData.isNullOrBlank()) {
            return boardingPass.qrCodeData
        }*/
        // Fallback: reconstruct from passId (offline / mock passes)
        return "${BuildConfig.URL}boarding/verify/${boardingPass.passId}"
    }
}